In [2]:
import numpy as np
import pandas as pd
data=np.arange(80,100).reshape(5,4)
d1=pd.DataFrame(data,index=['shan','kaen','tom','lexmi','ram'],columns=['OS','DSA','EDA','CN'])
print(d1)

       OS  DSA  EDA  CN
shan   80   81   82  83
kaen   84   85   86  87
tom    88   89   90  91
lexmi  92   93   94  95
ram    96   97   98  99

In [3]:
d1['CN']=np.nan
d1

       OS  DSA  EDA  CN
shan   80   81   82 NaN
kaen   84   85   86 NaN
tom    88   89   90 NaN
lexmi  92   93   94 NaN
ram    96   97   98 NaN

In [4]:
d1.loc['sam']=np.arange(60,64)
d1

       OS  DSA  EDA    CN
shan   80   81   82   NaN
kaen   84   85   86   NaN
tom    88   89   90   NaN
lexmi  92   93   94   NaN
ram    96   97   98   NaN
sam    60   61   62  63.0

In [5]:
d1.loc['nolan']=np.nan
d1

         OS   DSA   EDA    CN
shan   80.0  81.0  82.0   NaN
kaen   84.0  85.0  86.0   NaN
tom    88.0  89.0  90.0   NaN
lexmi  92.0  93.0  94.0   NaN
ram    96.0  97.0  98.0   NaN
sam    60.0  61.0  62.0  63.0
nolan   NaN   NaN   NaN   NaN

In [6]:
d1.isnull()

          OS    DSA    EDA     CN
shan   False  False  False   True
kaen   False  False  False   True
tom    False  False  False   True
lexmi  False  False  False   True
ram    False  False  False   True
sam    False  False  False  False
nolan   True   True   True   True

In [7]:
d1.notnull()

          OS    DSA    EDA     CN
shan    True   True   True  False
kaen    True   True   True  False
tom     True   True   True  False
lexmi   True   True   True  False
ram     True   True   True  False
sam     True   True   True   True
nolan  False  False  False  False

In [8]:
d1.isnull().sum()

OS     1
DSA    1
EDA    1
CN     6
dtype: int64

In [9]:
d1.isnull().sum().sum()

np.int64(9)

In [10]:
d1.count()

OS     6
DSA    6
EDA    6
CN     1
dtype: int64

In [11]:
d1.CN[d1.CN.notnull()]

sam    63.0
Name: CN, dtype: float64

In [12]:
d1.CN.dropna()

sam    63.0
Name: CN, dtype: float64

In [13]:
d1.dropna()

       OS   DSA   EDA    CN
sam  60.0  61.0  62.0  63.0

In [14]:
d1.dropna(how='all')

         OS   DSA   EDA    CN
shan   80.0  81.0  82.0   NaN
kaen   84.0  85.0  86.0   NaN
tom    88.0  89.0  90.0   NaN
lexmi  92.0  93.0  94.0   NaN
ram    96.0  97.0  98.0   NaN
sam    60.0  61.0  62.0  63.0

In [15]:
d1.loc['sam','CN']=np.nan
d1.dropna(how='all',axis=1)

         OS   DSA   EDA
shan   80.0  81.0  82.0
kaen   84.0  85.0  86.0
tom    88.0  89.0  90.0
lexmi  92.0  93.0  94.0
ram    96.0  97.0  98.0
sam    60.0  61.0  62.0
nolan   NaN   NaN   NaN

In [16]:
d1.dropna(thresh=3)

         OS   DSA   EDA  CN
shan   80.0  81.0  82.0 NaN
kaen   84.0  85.0  86.0 NaN
tom    88.0  89.0  90.0 NaN
lexmi  92.0  93.0  94.0 NaN
ram    96.0  97.0  98.0 NaN
sam    60.0  61.0  62.0 NaN

In [25]:
a1=np.array([10,20,30,np.nan,40])
s1=pd.Series(a1)
print(a1)
print(s1)

[10. 20. 30. nan 40.]
0    10.0
1    20.0
2    30.0
3     NaN
4    40.0
dtype: float64

In [26]:
print(s1.mean())
print(a1.mean())

25.0
nan

In [28]:
s2=d1.DSA
s2.sum()

np.float64(506.0)

In [29]:
s2.mean()

np.float64(84.33333333333333)

In [30]:
s2.cumsum()

shan      81.0
kaen     166.0
tom      255.0
lexmi    348.0
ram      445.0
sam      506.0
nolan      NaN
Name: DSA, dtype: float64

In [33]:
filledd1=d1.fillna(0)
filledd1

         OS   DSA   EDA   CN
shan   80.0  81.0  82.0  0.0
kaen   84.0  85.0  86.0  0.0
tom    88.0  89.0  90.0  0.0
lexmi  92.0  93.0  94.0  0.0
ram    96.0  97.0  98.0  0.0
sam    60.0  61.0  62.0  0.0
nolan   0.0   0.0   0.0  0.0

In [34]:
d1.mean()

OS     83.333333
DSA    84.333333
EDA    85.333333
CN           NaN
dtype: float64

In [35]:
filledd1.mean()

OS     71.428571
DSA    72.285714
EDA    73.142857
CN      0.000000
dtype: float64

In [39]:
d1.EDA.ffill()

shan     82.0
kaen     86.0
tom      90.0
lexmi    94.0
ram      98.0
sam      62.0
nolan    62.0
Name: EDA, dtype: float64

In [44]:
d1.loc['DSA','ram']=np.nan
d1.DSA.bfill()

shan     81.0
kaen     85.0
tom      89.0
lexmi    93.0
ram      97.0
sam      61.0
nolan     NaN
CN        NaN
DSA       NaN
Name: DSA, dtype: float64