In [12]:
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer,SimpleImputer
df=pd.DataFrame({'Car Model':[2022,2025,2023,np.nan,2022],'Price':[1000000,10000000,2500000,1800000,np.nan],'Engine capacity(in cc)':[np.nan,5900,2500,1600,800]})
df['Car Model']=df['Car Model'].astype('Int64')
df

   Car Model       Price  Engine capacity(in cc)
0       2022   1000000.0                     NaN
1       2025  10000000.0                  5900.0
2       2023   2500000.0                  2500.0
3       <NA>   1800000.0                  1600.0
4       2022         NaN                   800.0

In [15]:
mean_imputer=SimpleImputer(strategy="mean")
df["Price_mean"]=mean_imputer.fit_transform(df[["Price"]])
df

   Car Model       Price  Engine capacity(in cc)  Price_mean
0       2022   1000000.0                     NaN   1000000.0
1       2025  10000000.0                  5900.0  10000000.0
2       2023   2500000.0                  2500.0   2500000.0
3       <NA>   1800000.0                  1600.0   1800000.0
4       2022   3825000.0                   800.0   3825000.0

In [17]:
mode_imputer=SimpleImputer(strategy="most_frequent")
df["Car_model_mode"]=mode_imputer.fit_transform(df[["Car Model"]])
df

   Car Model       Price  Engine capacity(in cc)  Price_mean  Car_model_mode
0       2022   1000000.0                     NaN   1000000.0          2022.0
1       2025  10000000.0                  5900.0  10000000.0          2025.0
2       2023   2500000.0                  2500.0   2500000.0          2023.0
3       <NA>   1800000.0                  1600.0   1800000.0          2022.0
4       2022   3825000.0                   800.0   3825000.0          2022.0

In [19]:
median_imputer=SimpleImputer(strategy="median")
df["Engine_capacity_median"]=median_imputer.fit_transform(df[["Engine capacity(in cc)"]])
df

,Car Model,Price,Engine capacity(in cc),Price_mean,Car_model_mode,Engine_capacity_median
0,2022,1000000.0,NaN,1000000.0,2022.0,2050.0
1,2025,10000000.0,5900.0,10000000.0,2025.0,5900.0
2,2023,2500000.0,2500.0,2500000.0,2023.0,2500.0
3,<NA>,1800000.0,1600.0,1800000.0,2022.0,1600.0
4,2022,3825000.0,800.0,3825000.0,2022.0,800.0

In [21]:
num_cols = ["Price", "Engine capacity(in cc)"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Price_MICE"] = df_mice["Price"]
df["Engine Capacity(in cc)_MICE"] = df_mice["Engine capacity(in cc)"]
print(df)

   Car Model       Price  Engine capacity(in cc)  Price_mean  Car_model_mode  \
0       2022   1000000.0                     NaN   1000000.0          2022.0
1       2025  10000000.0                  5900.0  10000000.0          2025.0
2       2023   2500000.0                  2500.0   2500000.0          2023.0
3       <NA>   1800000.0                  1600.0   1800000.0          2022.0
4       2022   3825000.0                   800.0   3825000.0          2022.0

   Engine_capacity_median  Price_MICE  Engine Capacity(in cc)_MICE
0                  2050.0   1000000.0                   849.746329
1                  5900.0  10000000.0                  5900.000000
2                  2500.0   2500000.0                  2500.000000
3                  1600.0   1800000.0                  1600.000000
4                   800.0   3825000.0                   800.000000